### ISSUE TITLE
Non-Snapshot Release

### ISSUE THREAD

**Issue by hadronzoo** [valichek/component-compojure#1]
Thanks for this library! Could you release a non-snapshot version?

**Comment by valichek** [comment]
Hey, there are several issues when using compojure routes (not-found, files, resources) now. So maybe when I solve it there will be non-snapshot version.

**Comment by firesofmay** [comment]
@valichek Any update on this?

**Comment by valichek** [comment]
just released non-snapshot version, have fun, sorry for being so late
