### ISSUE TITLE
Incompatible with compojure.route/not-found

### ISSUE THREAD

**Issue by hadronzoo** [valichek/component-compojure#2]
The following fails to compile:

``` clojure
(ns ccompojure.test
  (:require [component.compojure :as ccompojure]
            [compojure.core :as compojure]
            [compojure.route :refer [not-found]]))

(ccompojure/defroutes ServerRoutes [db]
  (compojure/GET "/word" [] (get-word db))
  (compojure/GET "/count" [] (get-count db))
  (not-found "The page could not be found"))
```

Removing the `not-found` clause resolves the error.

**Comment by valichek** [comment]
Thank you for the message. It's not possible to use "not-found", "files" and "resources" in current version, just main macro funs from core (GET, POST, etc) except rfn. I will try to fix it.

**Comment by valichek** [comment]
Hey, check https://github.com/valichek/component-compojure for new usage directions

**Comment by hadronzoo** [comment]
Great, thanks!
